### ISSUE TITLE
Always returns the same language

### ISSUE THREAD

**Issue by matueszwin** [wiziple/browser-lang#1]
Hi, 

I'm using this plugin with gatsby and when I try to detect the browser language It always returns the same language even though I change the browsers setting. Does It base on something else not only browser or Am I missing something ? 

` import browserLang from 'browser-lang'; 
render() {
const detected = browserLang();
return(
 { detected }
)
}
`

**Comment by wiziple** [comment]
Can you console.log browserLang() and check what is printed?
